# Generated by Django 5.0.3 on 2024-03-20 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_area',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_categoria',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=255)),
                ('descripcion', models.TextField(null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha_inicio', models.DateField()),
                ('popularidad', models.DecimalField(decimal_places=2, max_digits=4)),
                ('profesor', models.CharField(max_length=150)),
                ('fecha_lanzamiento', models.DateField()),
                ('idioma', models.CharField(max_length=25)),
                ('subtitulo', models.CharField(max_length=25)),
                ('dificultad', models.CharField(max_length=50)),
                ('duracion', models.CharField(max_length=4)),
                ('estudiantes', models.CharField(max_length=6)),
                ('nota_a', models.CharField(max_length=200)),
                ('nota_b', models.CharField(max_length=200)),
                ('nota_c', models.CharField(max_length=200)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='alura.area')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='alura.categoria')),
            ],
            options={
                'db_table': 'tbl_curso',
            },
        ),
    ]
