# Generated by Django 5.0.3 on 2024-03-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alura', '0003_alter_cursoimagen_options_curso_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='sku',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
