# Generated by Django 5.0.3 on 2024-03-22 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alura', '0006_pedido_pedidodetalle'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pedido',
            table='tbl_pedido',
        ),
        migrations.AlterModelTable(
            name='pedidodetalle',
            table='tbl_pedido_detalle',
        ),
    ]
